dictionary = {
    'review': 'مرور',
    'input empty': 'ورودی خالی',
    'email not valid': 'ایمیل معتبر نیست',
    'not found': 'پیدا نشد',
    'password mismatch': 'عدم هماهنگی گذرواژه',
    'free shipping': 'رایگان کالا',
    'for orders over': 'برای سفارشات بیش از',
    '': '$',
    '20': '20',
    'en': 'EN',
    'usd': 'دلار آمریکا',
    'image coming soon': 'تصویر به زودی',
    'added to cart': 'اضافه شده به سبد خرید',
    'total': 'جمع',
    'discount': 'تخفیف',
    'together': 'با یکدیگر',
    'quantity': 'مقدار',
    'cart total': 'سبد خرید مجموع',
    'checkout': 'وارسی',
    'customers also bought': 'مشتریان نیز خریداری شدند',
    '000': '0.00',
    '0': '0',
    'sign in': 'ورود',
    'my account': 'حساب من',
    'wish list': 'لیست دلخواه',
    'my page': 'صفحه من',
    'rewards': 'پاداش',
    'messages': 'پیام ها',
    'sign out': 'خروج',
    'create an account': 'ایجاد یک حساب کاربری',
    '247': '24/7',
    'search from over 35000 products': 'جستجو از بیش از 35،000 محصول',
    'daily deal': 'معامله روزانه',
    'order history': 'تاریخچه سفارش ها',
    'reviews': 'نظرات',
    'help': 'کمک',
    'contact us': 'تماس با ما',
    'trending searches': 'جستجوهای مورد علاقه',
    'probiotics': 'پروبیوتیک ها',
    'collagen': 'کلاژن',
    'search history': 'سابقه جستجو',
    'clear search history': 'پاک کردن تاریخچه جستجو',
    'brands': 'مارک ها',
    'supplements': 'مکمل',
    'herbs': 'گیاهان',
    'bath': 'حمام',
    'beauty': 'زیبایی',
    'grocery': 'خواربار',
    'baby': 'عزیزم',
    'sports': 'ورزش ها',
    'home': 'خانه',
    'pets': 'حیوانات خانگی',
    'quick links': 'لینک های سریع',
    'iherbcom': 'iHerb.com',
    'herbs and supplements': 'گیاهان و مکمل ها',
    'drug interactions': 'تعاملات دارویی',
    'herbalgram': 'HerbalGram',
    'iherb blog': 'وبلاگ iHerb',
    'dr murray': 'دکتر موری',
    'all links': 'همه لینک ها',
    'categories': 'دسته بندی ها',
    'specials': 'ویژه',
    'new': 'جدید',
    'best sellers': 'بهترین فروشندگان',
    'trial items': 'موارد آزمون',
    'share': 'اشتراک گذاری',
    'copy and share this page': 'کپی و اشتراک گذاری این صفحه',
    'you are now signed in': 'شما در حال حاضر وارد شده اید',
    'copy and share this list with your rewards code': 'کپی و اشتراک این لیست با کد پاداش شما',
    'attached': 'متصل شده',
    'more about': 'بیشتر در مورد',
    'more about': 'بیشتر در مورد',
    'copy': 'کپی کنید',
    'shorten url': 'کوتاه کردن URL',
    'for iherb customers mdash share this page with others and save even more': 'برای مشتریان iHerb',
    'or': 'یا',
    'read more': 'ادامه مطلب',
    'worlds best value': 'بهترین ارزش جهان!',
    'email a friend': 'برای یک دوست ایمیل کنید',
    'saved': 'ذخیره',
    'your name': 'اسم شما',
    'your friend39s email address': 'دوست شما',
    'invalid email address': 'آدرس ایمیل نامعتبر',
    'personal message': 'پیام شخصی',
    'optional 500 max characters': 'اختیاری (500 کاراکتر حداکثر)',
    'send email': 'ایمیل بفرست',
    'thank you': 'متشکرم!',
    'your email is being processed': 'ایمیل شما در حال پردازش است',
    'iherbcom  vitamins supplements amp natural health products': 'iHerb.com - ویتامین ها، مکمل ها',
    'trending now': 'هم اکنون در جریان است',
    'the biggest gainers in iherbcom sales rank over the past 24 hours': 'بزرگترین فروشندگان در فروش iHerb.com در 24 ساعت گذشته رتبه بندی شده است.',
    'best selling': 'بهترین فروش',
    'see all': 'همه را ببین',
    'doloka': 'دلوکا',
    'live': 'زنده',
    'check out what others are buying in real time': 'بررسی کنید که دیگران در زمان واقعی خرید می کنند',
    'about doloka': 'درباره دلکا',
    'about us': 'دربارهی ما',
    'we give back': 'ما برگشتیم',
    'promote doloka': 'تبلیغ دلوکا',
    'careers': 'شغل',
    'suppliers': 'تامین کنندگان',
    'doloka resources': 'منابع DOLOKA',
    'doloka blog': 'وبلاگ دولوکا',
    'my doloka page': 'صفحه Doloka من است',
    'healthy links': 'لینک های سالم',
    'customer service': 'خدمات مشتری',
    'privacy policy': 'سیاست حفظ حریم خصوصی',
    'terms of use': 'شرایط استفاده',
    'supply chains act': 'قانون زنجیره تامین',
    'mobile apps': 'APP MOBILE',
    'connect with us': 'با ایالات متحده ارتباط برقرار کنید',
    'ask a question': 'یک سوال بپرس',
    'find answers from our knowledge base': 'یافتن پاسخ از پایگاه دانش ما.',
    'get help now raquo': 'اکنون راهنمایی کنید',
    'get help now raquo': 'اکنون راهنمایی کنید',
    'give 5 amp get 5': '5٪ بده',
    'learn more': 'بیشتر بدانید',
    'dolokair': 'doloka.ir',
    """copy copyright 19972017 iherb inc all rights reserved
                  iherbreg is a registered trademark of iherb inc trusted brands healthy rewards
                  and the iherbcom trusted brands healthy rewards logo are trademarks of iherb
                  inc disclaimer statements made or products sold through this
                  website have not been evaluated by the united states food and drug administration they are not
                  intended to diagnose treat cure or prevent any disease""": '',
    'read morenbspraquo': 'ادامه مطلب',
    'wellness': 'سلامتی',
    'fitness': 'تناسب',
    'nutrition': 'تغذیه',
    'in this article': 'در این مقاله',
    'sun 18 nov 2018 191635 gmt': 'خورشید، 18 نوامبر 2018 19:16:35 GMT',
    'what39s new': 'چی',
    'با طاعون مدرنیته و غذاهای این عصر مبارزه کنید ، ببینید که انجام این کار با جوانه چه راحت است': 'Ø¨Ø§ Ø · Ø§Ø¹ÙÙ † Ù ... Ø¯Ø ± Ù † ÛŒØªÙ ‡ Ù ØºØ¨ Ø§Ù ‡ Ø§ÙŒ Ø§ÙŒÙ † Ø¹ØμØ ± Ù ... Ø¨Ø§Ø ± Ø²Ù ‡ Ú © Ù † ',
    'blog': 'وبلاگ',
    'brands az': 'علامت های تجاری A-Z',
    'by': 'توسط',
    'you purchased this item on': 'شما این مورد را خریداری کرده اید',
    'view this order': 'مشاهده این سفارش',
    'shipping saver': 'درایور حمل و نقل',
    """shipping saver items cost less to ship so we can pass the savings
                  along to you this means that when you add a shipping saver item to your cart your
                  shipping cost will decrease""": 'اقلام صرفه جویی در حمل و نقل هزینه کمتر برای کشتی، بنابراین ما می توانیم پس انداز عبور',
    'msrp': 'MSRP:',
    'our price': 'قیمت ما:',
    'you save': 'شما ذخیره کنید:',
    'sorry this product is no longer in stock': 'متاسفم، این محصول دیگر موجود نیست.',
    'add to cart': 'افزودن به سبد خرید',
    'call': 'زنگ زدن',
    'add to wish list': 'افزودن به لیست دلخواه',
    'create a new list': 'ایجاد یک لیست جدید:',
    'list name required': 'نام لیست مورد نیاز است',
    'create list': 'ایجاد لیست',
    'earn': 'بدست آوردن',
    'loyalty credit': 'اعتبار وفاداری',
    'loyalty program': 'برنامه وفاداری',
    'you earn loyalty credit for every order you place at iherb': '- شما هر گونه سفارشی را که در iHerb قرار می دهید، اعتبار وفاداری کسب می کنید!',
    'nbspnbsployalty credit is equal to 5 of the value of your order after discounts and credits applied excluding shipping charges': '-',
    'your loyalty credit will be applied towards your next order as soon as your current order has shipped': '- اعتبار وفاداری شما به منظور سفارش بعدی شما به محض ارسال سفارش فعلی شما اعمال خواهد شد.',
    'your loyalty credits are valid for up to 90 days from the date of your last purchase': '- اعتبار وفاداری شما تا 90 روز از تاریخ آخرین خرید شما معتبر است.',
    'write a review': 'نوشتن نظر',
    'write a review': 'نوشتن نظر',
    'in stock': 'در انبار',
    'expiration date': 'تاریخ انقضا',
    """pthe length of time for the expiration date or quotbest used beforequot date depends on
                              the type of product as well as the brandp
                           pperishable items such as flax oils or certain probiotics generally have shorter
                              expiration dates although our warehouse is fully airconditioned these more fragile
                              items are put in cold storage freezer or refrigeration unit for maximum freshnessp
                           pour receiving department does its best to verify and then enter the correct expiration
                              dates for all incoming products however discrepancies do occur from time to time this
                              being said the exceptionally high turnover at iherb ensures that our inventory is among
                              the freshest in the industryp""": ' طول زمان برای تاریخ انقضا یا',
    'shipping weight': 'وزن حمل و نقل',
    'lbs': 'پوند',
    'switch to metric units': 'به واحد متریک بروید',
    """the shipping weight includes the product protective packaging
                           material and the actual shipping box in addition the shipping weight may be adjusted for
                           the dimensional weight eg length width ampamp height of a package it is important to
                           note that certain types of products eg glass containers liquids fragile refrigerated or
                           ice packed will often require protective packaging material as such these products will
                           reflect a higher shipping weight compared to the unprotected product""": 'وزن حمل و نقل شامل محصول، بسته بندی محافظتی است ',
    'product code': 'کد محصول',
    'upc code': 'کد UPC',
    'package quantity': 'تعداد بسته بندی',
    'dimensions': 'ابعاد',
    'in': 'که در',
    'related products': 'محصولات مرتبط',
    'product overview': 'بررسی اجمالی محصولات',
    'visit manufacturer39s website': 'بازدید سازنده',
    'contain': 'حاوی:',
    'amount per serving': 'مقدار در هر خدمت',
    'dv': '٪ DV',
    'daily value dv not establishedbr †this product uses gnosis spas l5methyltetrahydrofolic acid glucosamine saltbr ††this product uses albionrsquos traacs calcium bisglycinate chelate chromium nicotinate glycinate chelate copper bisglycinate chelate manganese bisglycinate chelate magnesium bisglycinate chelate molybdenum glycinate chelate and zinc bisglycinate chelate traacs is a registered trademark of albion international inc br †††this product uses albionrsquos bororganic boron glycinate complex bororganic is a trademark of albion international incbr': '* ارزش روزانه (DV) ثابت نشده است. <br/> این محصول با استفاده از اسید L-5-Methyltetrahydrofolic اسید Gnosis S.p.A.، نمک گلوکزامین <br/> â € â € این محصول با استفاده از Albion',
    'iherb customer': 'مشتری iHerb',
    'an iherb customer has completed a transaction and has accepted the': 'مشتری iHerb معامله را تکمیل کرده است و پذیرفته شده است',
    'terms  conditions': 'مقررات',
    'iherb customer reviews': 'نظرات مشتریان iHerb',
    '5': '5',
    'star': 'ستاره',
    '4': '4',
    '3': '3',
    '2': '2',
    '1': '1',
    'see all reviews': 'تمام نظرات را ببینید',
    'infinite beauty': 'زیبایی بی نهایت',
    'upload your face': 'صورت خود را آپلود کنید',
    'click': 'کلیک',
    'conditions': 'شرایط'
}
